set(CRYPTO_SOURCES
	crypto/mp_2expt.c
	crypto/mp_abs.c
	crypto/mp_add.c
	crypto/mp_add_d.c
	crypto/mp_addmod.c
	crypto/mp_and.c
	crypto/mp_clamp.c
	crypto/mp_clear.c
	crypto/mp_clear_multi.c
	crypto/mp_cmp.c
	crypto/mp_cmp_d.c
	crypto/mp_cmp_mag.c
	crypto/mp_cnt_lsb.c
	crypto/mp_complement.c
	crypto/mp_copy.c
	crypto/mp_count_bits.c
	crypto/mp_cutoffs.c
	crypto/mp_div.c
	crypto/mp_div_2.c
	crypto/mp_div_2d.c
	crypto/mp_div_d.c
	crypto/mp_dr_is_modulus.c
	crypto/mp_dr_reduce.c
	crypto/mp_dr_setup.c
	crypto/mp_error_to_string.c
	crypto/mp_exch.c
	crypto/mp_expt_n.c
	crypto/mp_exptmod.c
	crypto/mp_exteuclid.c
	crypto/mp_fread.c
	crypto/mp_from_sbin.c
	crypto/mp_from_ubin.c
	crypto/mp_fwrite.c
	crypto/mp_gcd.c
	crypto/mp_get_double.c
	crypto/mp_get_i32.c
	crypto/mp_get_i64.c
	crypto/mp_get_l.c
	crypto/mp_get_mag_u32.c
	crypto/mp_get_mag_u64.c
	crypto/mp_get_mag_ul.c
	crypto/mp_grow.c
	crypto/mp_hash.c
	crypto/mp_init.c
	crypto/mp_init_copy.c
	crypto/mp_init_i32.c
	crypto/mp_init_i64.c
	crypto/mp_init_l.c
	crypto/mp_init_multi.c
	crypto/mp_init_set.c
	crypto/mp_init_size.c
	crypto/mp_init_u32.c
	crypto/mp_init_u64.c
	crypto/mp_init_ul.c
	crypto/mp_invmod.c
	crypto/mp_is_square.c
	crypto/mp_kronecker.c
	crypto/mp_lcm.c
	crypto/mp_log.c
	crypto/mp_log_n.c
	crypto/mp_lshd.c
	crypto/mp_mod.c
	crypto/mp_mod_2d.c
	crypto/mp_montgomery_calc_normalization.c
	crypto/mp_montgomery_reduce.c
	crypto/mp_montgomery_setup.c
	crypto/mp_mul.c
	crypto/mp_mul_2.c
	crypto/mp_mul_2d.c
	crypto/mp_mul_d.c
	crypto/mp_mulmod.c
	crypto/mp_neg.c
	crypto/mp_or.c
	crypto/mp_pack.c
	crypto/mp_pack_count.c
	crypto/mp_prime_fermat.c
	crypto/mp_prime_frobenius_underwood.c
	crypto/mp_prime_is_prime.c
	crypto/mp_prime_miller_rabin.c
	crypto/mp_prime_next_prime.c
	crypto/mp_prime_rabin_miller_trials.c
	crypto/mp_prime_rand.c
	crypto/mp_prime_strong_lucas_selfridge.c
	crypto/mp_radix_size.c
	crypto/mp_radix_size_overestimate.c
	crypto/mp_rand.c
	crypto/mp_rand_source.c
	crypto/mp_read_radix.c
	crypto/mp_reduce.c
	crypto/mp_reduce_2k.c
	crypto/mp_reduce_2k_l.c
	crypto/mp_reduce_2k_setup.c
	crypto/mp_reduce_2k_setup_l.c
	crypto/mp_reduce_is_2k.c
	crypto/mp_reduce_is_2k_l.c
	crypto/mp_reduce_setup.c
	crypto/mp_root_n.c
	crypto/mp_rshd.c
	crypto/mp_sbin_size.c
	crypto/mp_set.c
	crypto/mp_set_double.c
	crypto/mp_set_i32.c
	crypto/mp_set_i64.c
	crypto/mp_set_l.c
	crypto/mp_set_u32.c
	crypto/mp_set_u64.c
	crypto/mp_set_ul.c
	crypto/mp_shrink.c
	crypto/mp_signed_rsh.c
	crypto/mp_sqrmod.c
	crypto/mp_sqrt.c
	crypto/mp_sqrtmod_prime.c
	crypto/mp_sub.c
	crypto/mp_sub_d.c
	crypto/mp_submod.c
	crypto/mp_to_radix.c
	crypto/mp_to_sbin.c
	crypto/mp_to_ubin.c
	crypto/mp_ubin_size.c
	crypto/mp_unpack.c
	crypto/mp_xor.c
	crypto/mp_zero.c
	crypto/s_mp_add.c
	crypto/s_mp_copy_digs.c
	crypto/s_mp_div_3.c
	crypto/s_mp_div_recursive.c
	crypto/s_mp_div_school.c
	crypto/s_mp_div_small.c
	crypto/s_mp_exptmod.c
	crypto/s_mp_exptmod_fast.c
	crypto/s_mp_fp_log.c
	crypto/s_mp_fp_log_d.c
	crypto/s_mp_get_bit.c
	crypto/s_mp_invmod.c
	crypto/s_mp_invmod_odd.c
	crypto/s_mp_log_2expt.c
	crypto/s_mp_montgomery_reduce_comba.c
	crypto/s_mp_mul.c
	crypto/s_mp_mul_balance.c
	crypto/s_mp_mul_comba.c
	crypto/s_mp_mul_high.c
	crypto/s_mp_mul_high_comba.c
	crypto/s_mp_mul_karatsuba.c
	crypto/s_mp_mul_toom.c
	crypto/s_mp_prime_is_divisible.c
	crypto/s_mp_prime_tab.c
	crypto/s_mp_radix_map.c
	crypto/s_mp_radix_size_overestimate.c
	crypto/s_mp_rand_platform.c
	crypto/s_mp_sqr.c
	crypto/s_mp_sqr_comba.c
	crypto/s_mp_sqr_karatsuba.c
	crypto/s_mp_sqr_toom.c
	crypto/s_mp_sub.c
	crypto/s_mp_zero_buf.c
	crypto/s_mp_zero_digs.c
)

set(CRYPTO_HEADERS
	crypto/tommath.h
	crypto/tommath_c89.h
	crypto/tommath_class.h
	crypto/tommath_cutoffs.h
	crypto/tommath_private.h
	crypto/tommath_superclass.h
)
